#!/bin/bash

# version 1.00 septembre 2026
# bash "chemin"/facila_install FICHIER_TAR

proc_check ()
{
ERROR=$1
shift
"$@" 2>/dev/null || { echo "  vous devez d'abord installer : $ERROR" ; exit ; }
}

proc_facila ()
{
OK_FACILA=1
if [ "$FACILA" = "" ]
then OK_FACILA=0
     FACILA=$PWD/facila
     echo "  ajout de FACILA dans .bashrc"
     printf "\n# FACILA\nexport FACILA=$FACILA\n" >> ~/.bashrc
fi

SAVE=$FACILA/save
if [ ! -d $SAVE ]
then echo "  création des répertoires de facila"
     mkdir -p $SAVE
     cd $SAVE 
     mkdir archive data delete install old version
fi
}

proc_save_old ()
{
OLD=$DIR_ZIP/facila_$APPLI
[ -f $OLD ] && mapfile -t LIST < $OLD || LIST=($APPLI)
OK_OLD=0
for F in "${LIST[@]}"
do if [ -d $F -o -f $F ]
   then OK_OLD=1
        mkdir -p $SAVE/old/$F # création des répertoires contenus dans $F
        rmdir    $SAVE/old/$F # suppression du dernier repertoire de $F
        mv $F    $SAVE/old/$F.`date +%y%m%d_%H%M` 2> /dev/null
   fi
done
[ $OK_OLD = 1 ] && echo "  sauvegarde de l'ancienne version dans $SAVE/old"
}

proc_lang ()
{
[ "$LG" = "$LANG"     ] && return
[ -d "$APPLI/var/$LG" ] && return
echo "  copie du répertoire d'origine $LG dans la langue de la machine $LANG"
echo "    votre langue est $LANG"
echo "    vous pouvez traduire les fichiers ( menu , aide , ... )"
cp -R $APPLI/var/$LG $APPLI/var/$LANG
}

proc_save_new ()
{
echo "  sauvegarde de la nouvelle version dans $SAVE/install"
cd $TELE
mv $ZIP $SAVE/install/$ZIP.`date +%y%m%d_%H%M` 2> /dev/null
rm -rf $APPLI-main
}

#################################################################################

     LG=fr_FR.UTF-8
   TELE=$(dirname $(realpath $0))
    TAR=$1
  APPLI=`echo $TAR | cut -f1   -d.`
    EXT=`echo $TAR | cut -f4-5 -d.`
    ZIP=$APPLI-main.zip
DIR_ZIP=$TELE/$APPLI-main

umask 0022

[ ! -s "$TELE/$ZIP"  ] && { echo "le fichier $ZIP n'existe pas" ; exit ; }
unzip -u $TELE/$ZIP -d $TELE
echo

if [ -f $DIR_ZIP/install_check ]
then echo "vérification des dépendances"
     . $DIR_ZIP/install_check
fi

printf "répertoire où est installé $APPLI , Entrée = $HOME : " 
read DIR_APPLI 
[ "$DIR_APPLI" = '' ] && cd || cd $DIR_APPLI
echo

[ ! -s "$DIR_ZIP/$TAR"  ] && { echo "le fichier $TAR n'existe pas"        ; exit ; }
[ "$EXT" != "tar.gz"    ] && { echo "le fichier $TAR doit être un tar.gz" ; exit ; }

echo "verification de facila"
proc_facila
cd $FACILA

echo "installation de $TAR"
proc_save_old
tar -pxzf $DIR_ZIP/$TAR
proc_lang
proc_save_new
 
# init
INIT=$FACILA/$APPLI/prg/appli_init.sh
[ -f $INIT ] && . $INIT

# command
COM=$FACILA/$APPLI/prg/$APPLI
if [ -s "$COM" ]
then echo "application : $APPLI"
     echo "commande    : $COM"
     [ $OK_FACILA = 0 ] && echo "fermer et relancer le shell pour exécuter $APPLI"
fi

rm $TELE/facila_install
