#!/bin/bash

# version 3.00 septembre 2026
# bash facila_install FICHIER_TAR

proc_check ()
{
ERROR=$1
shift
"$@" 2>/dev/null || { echo "  vous devez d'abord installer : $ERROR" ; exit ; }
}

proc_facila ()
{
OK_FACILA=1
if [ "$FACILA" = "" ]
then OK_FACILA=0
     FACILA=$PWD/facila
     echo "  ajout de FACILA dans .bashrc"
     printf "\n# FACILA\nexport FACILA=$FACILA\n" >> ~/.bashrc
fi

SAVE=$FACILA/save
if [ ! -d $SAVE ]
then echo "  création des répertoires de facila"
     mkdir -p $SAVE
     cd $SAVE 
     mkdir archive data delete install old version
fi
}

proc_save_old ()
{
OLD=$DIR/facila_$APPLI
[ -f $OLD ] && mapfile -t LIST < $OLD || LIST=($APPLI)

OK_OLD=0
for F in "${LIST[@]}"
do if [ -d $F -o -f $F ]
   then OK_OLD=1
        mkdir -p $SAVE/old/$F # création des répertoires contenus dans $F
        rmdir    $SAVE/old/$F # suppression du dernier repertoire de $F
        mv $F    $SAVE/old/$F.`date +%y%m%d_%H%M` 2> /dev/null
   fi
done
[ $OK_OLD = 1 ] && echo "  sauvegarde de l'ancienne version dans $SAVE/old"
}

proc_init ()
{
INIT=$FACILA/$APPLI/prg/appli_init.sh
[ -f $INIT ] && . $INIT
}

proc_lang ()
{
[ "$LG" = "$LANG"     ] && return
[ -d "$APPLI/var/$LG" ] && return

echo "copie du répertoire d'origine $LG dans la langue de la machine $LANG"
cp -R $APPLI/var/$LG $APPLI/var/$LANG
echo "  votre langue est $LANG"
echo "  vous pouvez traduire les fichiers ( menu , aide , ... )"
}

proc_save_new ()
{
cd ..
mv $APPLI-main.zip $SAVE/install
mv $TAR            $SAVE/version
rm -rf $APPLI-main
}

proc_command ()
{
COM=$FACILA/$APPLI/prg/$APPLI
[ ! -s "$COM" ] && return

echo "  application : $APPLI"
echo "  commande    : $COM"
[ $OK_FACILA = 0 ] && echo "  fermer et relancer le shell pour exécuter $APPLI"
}

#################################################################################

   LG=fr_FR.UTF-8
  TAR=$1
APPLI=`echo $TAR | cut -f1 -d.`
  EXT=`echo $TAR | cut -f4-5 -d.`
  DIR=$PWD/$APPLI-main

[ ! -s "$DIR/$TAR"   ] && { echo "fichier $TAR absent" ; exit ; }
[ "$EXT" != "tar.gz" ] && { echo "le fichier $TAR doit être un tar.gz" ; exit ; }

echo "vérification des dépendances"
[ -f $DIR/install_check ] && . $DIR/install_check

echo "verification de facila"
proc_facila
cd $FACILA

proc_save_old

echo "installation de $TAR"
tar -pxzf $DIR/$TAR

proc_init
proc_lang
proc_save_new
proc_command
